# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eRegistrations
main_title: Help eRegistrations
email: info@eregistrations.com
description:
  en: Help for eRegistrations
  es: Ayada pro eRegistrations
baseurl: "" # the subpath of your site, e.g. /blog
url: "help.eregistrations.org" # the base hostname & protocol for your site
github_username:  egovernment
port: 4001
index:
  en:
  es: inicio.html

# Build settings
markdown: kramdown

# Collections
collections:
  documentation:
    output: true
    title:
        en: 'Documentation'
        es: 'Documentación'
    baseurl:
        en: '/documentation'
        es: '/documentacion'
  how-to:
    output: true
    title:
        en: 'How-to'
        es: 'Cómo'
    link-title:
        en: 'Search'
        es: 'Buscar'
    baseurl:
        en: '/how-to'
        es: '/como'
  trainings:
    output: true
    title:
        en: 'Trainings'
        es: 'Entrenamientos'
    baseurl:
        en: '/trainings'
        es: '/entrenamientos'

